name: My Workflow

on:
  push:
    branches:
      - razi

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Create virtual environment
      run: python -m venv venv
      # This creates a virtual environment in a folder called `venv`.

    - name: Activate virtual environment
      run: |
        . venv/bin/activate
        pip install --upgrade pip
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip freeze > requirements.txt
        
    - name: Create pylintrc file
      run: |
        pylint --generate-rcfile > .pylintrc
        
    - name: Linter test
      run: |
        pylint --disable=
          - C0301 # Line too long
          - C0303 # Trailing whitespace
          - C0305 # Trailing newlines
          - C0114 # Missing module docstring
          - R0402 # Use 'from module import name' instead
          - C0116 # Missing function or method docstring
          - W0621 # Redefining name from outer scope
          - E1101 # Module has no member
          - C0103 # Invalid function name
          - C0321 # Multiple statements on a single line
          - C0209 # Formatting a regular string which could be a f-string
        $(git ls-files '*.py')


